@echo off
setlocal

REM ==========================================================
REM
REM IHealDrunk Media Builder
REM Version 3.8.1
REM
REM Generates IHealDrunk_Media.lua from the media folders.
REM
REM ==========================================================

set "LUA=IHealDrunk_Media.lua"

echo.
echo ======================================
echo Building %LUA%
echo ======================================
echo.

REM Delete old file
if exist "%LUA%" del "%LUA%"

REM ----------------------------------------------------------
REM Header
REM ----------------------------------------------------------

(
echo -- ==========================================================
echo -- Automatically generated by update_media.bat
echo -- Do not edit this file manually.
echo -- ==========================================================
echo.
echo local LSM = LibStub:GetLibrary("LibSharedMedia-3.0"^)
echo.
) > "%LUA%"

REM ----------------------------------------------------------
REM Fonts
REM ----------------------------------------------------------

if exist "Fonts\" (
    echo --FONTS>>"%LUA%"
    for %%f in ("Fonts\*.*") do (
        echo LSM:Register("font","%%~nf",[[Interface\AddOns\IHealDrunk_Media\Fonts\%%~nxf]]^)>>"%LUA%"
    )
    echo.>>"%LUA%"
)

REM ----------------------------------------------------------
REM Statusbars
REM ----------------------------------------------------------

if exist "Statusbar\" (
    echo --STATUSBAR>>"%LUA%"
    for %%f in ("Statusbar\*.*") do (
        echo LSM:Register("statusbar","%%~nf",[[Interface\AddOns\IHealDrunk_Media\Statusbar\%%~nxf]]^)>>"%LUA%"
    )
    echo.>>"%LUA%"
)

REM ----------------------------------------------------------
REM Sounds
REM ----------------------------------------------------------

if exist "Sounds\" (
    echo --SOUNDS>>"%LUA%"
    for %%f in ("Sounds\*.*") do (
        echo LSM:Register("sound","%%~nf",[[Interface\AddOns\IHealDrunk_Media\Sounds\%%~nxf]]^)>>"%LUA%"
    )
    echo.>>"%LUA%"
)

REM ----------------------------------------------------------
REM Details
REM ----------------------------------------------------------

if exist "Details\" (
    echo --DETAILS>>"%LUA%"
    for %%f in ("Details\*.*") do (
        echo LSM:Register("details","%%~nf",[[Interface\AddOns\IHealDrunk_Media\Details\%%~nxf]]^)>>"%LUA%"
    )
    echo.>>"%LUA%"
)

REM ----------------------------------------------------------
REM Icons
REM ----------------------------------------------------------

if exist "Icons\" (
    echo --ICONS>>"%LUA%"
    for %%f in ("Icons\*.*") do (
        echo LSM:Register("icon","%%~nf",[[Interface\AddOns\IHealDrunk_Media\Icons\%%~nxf]]^)>>"%LUA%"
    )
    echo.>>"%LUA%"
)

echo ======================================
echo Build Complete!
echo Generated:
echo %LUA%
echo ======================================
echo.

pause