local LSM = LibStub("LibSharedMedia-3.0") 

LSM:Register("font", "big_noodle_titling", [[Interface\Addons\ElvUI_Media\Fonts\big_noodle_titling.ttf]]) 
LSM:Register("font", "big_noodle_titling_oblique", [[Interface\Addons\ElvUI_Media\Fonts\big_noodle_titling_oblique.ttf]]) 
LSM:Register("font", "GothamN-Black", [[Interface\Addons\ElvUI_Media\Fonts\GothamN-Black.ttf]]) 
LSM:Register("font", "GothamNarrow Ultra", [[Interface\Addons\ElvUI_Media\Fonts\GothamNarrow Ultra.otf]]) 
LSM:Register("font", "GothamNarrow-Black", [[Interface\Addons\ElvUI_Media\Fonts\GothamNarrow-Black.ttf]]) 
LSM:Register("font", "GothamXN Ultra", [[Interface\Addons\ElvUI_Media\Fonts\GothamXN Ultra.ttf]]) 
LSM:Register("font", "GothamXN-Black", [[Interface\Addons\ElvUI_Media\Fonts\GothamXN-Black.ttf]]) 
LSM:Register("font", "GothamXNarrow-Black", [[Interface\Addons\ElvUI_Media\Fonts\GothamXNarrow-Black.ttf]]) 
LSM:Register("font", "KMT-GothamN-Black", [[Interface\Addons\ElvUI_Media\Fonts\KMT-GothamN-Black.ttf]]) 
LSM:Register("font", "KMT-GothamNarrow Ultra", [[Interface\Addons\ElvUI_Media\Fonts\KMT-GothamNarrow Ultra.otf]]) 
LSM:Register("font", "KMT-GothamNarrow-Black", [[Interface\Addons\ElvUI_Media\Fonts\KMT-GothamNarrow-Black.ttf]]) 
LSM:Register("font", "KMT-GothamXN Ultra", [[Interface\Addons\ElvUI_Media\Fonts\KMT-GothamXN Ultra.ttf]]) 
LSM:Register("font", "KMT-GothamXN-Black", [[Interface\Addons\ElvUI_Media\Fonts\KMT-GothamXN-Black.ttf]]) 
LSM:Register("font", "KMT-GothamXNarrow-Black", [[Interface\Addons\ElvUI_Media\Fonts\KMT-GothamXNarrow-Black.ttf]]) 
LSM:Register("font", "Lovely Bubbles Italic", [[Interface\Addons\ElvUI_Media\Fonts\Lovely Bubbles Italic.ttf]]) 
LSM:Register("font", "Lovely Bubbles", [[Interface\Addons\ElvUI_Media\Fonts\Lovely Bubbles.ttf]]) 
LSM:Register("font", "Nice Sugar", [[Interface\Addons\ElvUI_Media\Fonts\Nice Sugar.ttf]]) 

LSM:Register("statusbar", "KMT35", [[Interface\Addons\ElvUI_Media\Statusbar\KMT35.tga]]) 
LSM:Register("statusbar", "KMT47", [[Interface\Addons\ElvUI_Media\Statusbar\KMT47.tga]]) 
LSM:Register("statusbar", "n33", [[Interface\Addons\ElvUI_Media\Statusbar\n33.tga]]) 
LSM:Register("statusbar", "One", [[Interface\Addons\ElvUI_Media\Statusbar\One.tga]]) 
LSM:Register("statusbar", "PaqUI", [[Interface\Addons\ElvUI_Media\Statusbar\PaqUI.tga]]) 

LSM:Register("sounds", "KMT-sylvanas_fth", [[Interface\Addons\ElvUI_Media\Sounds\KMT-sylvanas_fth.mp3]]) 

LSM:Register("details", "kmt-details", [[Interface\Addons\ElvUI_Media\Deatils\kmt-details.tga]]) 
LSM:Register("details", "kmt-details2", [[Interface\Addons\ElvUI_Media\Deatils\kmt-details2.tga]]) 
LSM:Register("details", "kmt-details3", [[Interface\Addons\ElvUI_Media\Deatils\kmt-details3.tga]]) 
LSM:Register("details", "kmt-details4", [[Interface\Addons\ElvUI_Media\Deatils\kmt-details4.blp]]) 
LSM:Register("details", "kmt-spec", [[Interface\Addons\ElvUI_Media\Deatils\kmt-spec.tga]]) 
