@echo off
setlocal

echo Updating ElvUI Media...
echo.

::=========================================================
:: Configuration
::=========================================================

set "LUA=ElvUI_Media.lua"

::=========================================================
:: Create new Lua file
::=========================================================

echo --========================================================= > "%LUA%"
echo -- ElvUI Media >> "%LUA%"
echo -- This file is automatically generated by update_media.bat >> "%LUA%"
echo -- Do not edit this file manually. >> "%LUA%"
echo --========================================================= >> "%LUA%"
echo. >> "%LUA%"
echo local LSM = LibStub("LibSharedMedia-3.0") >> "%LUA%"
echo. >> "%LUA%"

::=========================================================
:: Fonts
::=========================================================

if exist "Fonts\" (
    echo --FONTS>> "%LUA%"
    for %%F in (Fonts\*.*) do (
        echo LSM:Register("font","%%~nF",[[Interface\Addons\ElvUI_Media\Fonts\%%~nxF]])>> "%LUA%"
    )
    echo.>> "%LUA%"
)

::=========================================================
:: Statusbars
::=========================================================

if exist "Statusbar\" (
    echo --STATUSBAR>> "%LUA%"
    for %%F in (Statusbar\*.*) do (
        echo LSM:Register("statusbar","%%~nF",[[Interface\Addons\ElvUI_Media\Statusbar\%%~nxF]])>> "%LUA%"
    )
    echo.>> "%LUA%"
)

::=========================================================
:: Sounds
::=========================================================

if exist "Sounds\" (
    echo --SOUNDS>> "%LUA%"
    for %%F in (Sounds\*.*) do (
        echo LSM:Register("sound","%%~nF",[[Interface\Addons\ElvUI_Media\Sounds\%%~nxF]])>> "%LUA%"
    )
    echo.>> "%LUA%"
)

::=========================================================
:: Details
::=========================================================

if exist "Details\" (
    echo --DETAILS>> "%LUA%"
    for %%F in (Details\*.*) do (
        echo LSM:Register("details","%%~nF",[[Interface\Addons\ElvUI_Media\Details\%%~nxF]])>> "%LUA%"
    )
    echo.>> "%LUA%"
)

::=========================================================
:: Icons
::=========================================================

if exist "Icons\" (
    echo --ICONS>> "%LUA%"
    for %%F in (Icons\*.*) do (
        echo LSM:Register("icon","%%~nF",[[Interface\Addons\ElvUI_Media\Icons\%%~nxF]])>> "%LUA%"
    )
    echo.>> "%LUA%"
)

::=========================================================
:: Finished
::=========================================================

echo ElvUI_Media.lua successfully regenerated.
echo.

pause
endlocal